on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install dependencies in each directory
        run: |
          for dir in */; do
            if [ -f "$dir/package.json" ]; then
              echo "Installing dependencies in $dir"
              cd $dir
              npm install
              cd ..
            fi
          done
